version: '3'
services:
  discovery:
    image: springio/eureka-spring-boot-docker
    ports:
      - 8761:8761
    networks:
      - infobox
  service:
    image: springio/service-spring-boot-docker
    environment:
      - JAVA_OPTS=
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
    ports:
      - 8081:8081
    networks:
      - infobox
  glaven:
    image: springio/glaven-spring-boot-docker
    environment:
      - JAVA_OPTS=
      - EUREKA_SERVER=http://discovery:8761/eureka
    restart: on-failure
    depends_on:
      - discovery
    ports:
      - 8082:8082
    networks:
      - infobox

networks:
  infobox:
    driver: bridge